### ISSUE TITLE
Dynamic disable state

### ISSUE THREAD

**Issue by Taxman972** [ahmad-sa3d/rcswitcher#1]
Hi,

Could you had this option disable/enable the rcswitcher like :
`$input.prop( 'disable', 'true' ).change();
$input.prop( 'disable', 'false' ).change();`

**Comment by ahmad-sa3d** [comment]
Yeas it works and in demo you will see two examples one for radio and other to checkbox

Note that for logical purpose this feature on radio inputs will only turning it on as radio buttons shouldnot be disabled and on disabling if you open js console you will notice alog message as radio buttons are disabling only by enabling another sibiling

**Comment by ahmad-sa3d** [comment]
Aha sorry i thought you mean dynamic check
Ok i will try to implement this feature, thanks

**Comment by ahmad-sa3d** [comment]
Ok Now Disable And Enable Feature is Added and I Update Plugin To Version 4
